#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
udiskie &
picom &
light-locker &
wal -R &
$HOME/.config/polybar/launch.sh

background=282828
foreground=$(xrdb -query | grep "foreground" | cut -f2 | sed -r 's/#//' | head -n 1)
color0=$(xrdb -query | grep "color0" | cut -f2 | sed -r 's/#//' | head -n 1)
color1=$(xrdb -query | grep "color1" | cut -f2 | sed -r 's/#//' | head -n 1)
color2=$(xrdb -query | grep "color2" | cut -f2 | sed -r 's/#//' | head -n 1)
color3=$(xrdb -query | grep "color3" | cut -f2 | sed -r 's/#//' | head -n 1)
color4=$(xrdb -query | grep "color4" | cut -f2 | sed -r 's/#//' | head -n 1)
color5=$(xrdb -query | grep "color5" | cut -f2 | sed -r 's/#//' | head -n 1)
color6=$(xrdb -query | grep "color6" | cut -f2 | sed -r 's/#//' | head -n 1)
color7=$(xrdb -query | grep "color7" | cut -f2 | sed -r 's/#//' | head -n 1)
color8=$(xrdb -query | grep "color8" | cut -f2 | sed -r 's/#//' | head -n 1)

bspc monitor -d term web code media

#### BSPWM configuration ####
# bspc config border_radius 8
bspc config border_width    1
bspc config window_gap      3
bspc config borderless_monocle		true
bspc config gapless_monocle		    false
bspc config single_monocle		    true
bspc config pointer_follows_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# some extra top space for bar
bspc config top_padding    0
bspc config right_padding  0
bspc config left_padding   0
bspc config bottom_padding 0


#### BSPWM coloring ####
bspc config normal_border_color "#$color2"
bspc config active_border_color "#$color9"
bspc config focused_border_color "#$color9"
bspc config presel_feedback_color "#$color5"
bspc config urgent_border_color   "#dd2727"

# bspc rule -a Termite state=floating center=true
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a Chromium desktop='^1' follow=on
bspc rule -a code-oss desktop='^3' follow=on
bspc rule -a vlc desktop='^4' follow=on
bspc rule -a imv desktop='^4' follow=on
bspc rule -a llpp desktop='^4' follow=on
bspc rule -a libreoffice-startcenter desktop='^4' follow=on
